// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Eduprompt.Domain.Entities;

public partial class Aihistory
{
    public int AihistoryId { get; set; }

    public int UserId { get; set; }

    public int? ConversationId { get; set; }

    public int? PromptInstanceId { get; set; }

    public string UserMessage { get; set; }

    public string Airesponse { get; set; }

    public DateTime ExecutedAt { get; set; }

    public int? ProcessingTimeMs { get; set; }

    public string Status { get; set; }

    public virtual Conversation Conversation { get; set; }

    public virtual PromptInstance PromptInstance { get; set; }

    public virtual User User { get; set; }
}