// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Eduprompt.Domain.Entities;

public partial class Apikey
{
    public int ApikeyId { get; set; }

    public int PackageId { get; set; }

    public string Apiprovider { get; set; }

    public string KeyHash { get; set; }

    public int? UsageLimit { get; set; }

    public int CurrentUsage { get; set; }

    public DateTime? ExpiresAt { get; set; }

    public virtual Package Package { get; set; }
}