// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Eduprompt.Domain.Entities;

public partial class Conversation
{
    public int ConversationId { get; set; }

    public int UserId { get; set; }

    public string Title { get; set; }

    public DateTime StartedAt { get; set; }

    public DateTime? LastActivity { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Aihistory> Aihistories { get; set; } = new List<Aihistory>();

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();

    public virtual User User { get; set; }
}