// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Eduprompt.Domain.Entities;

public partial class ExpectedOutput
{
    public int OutputId { get; set; }

    public int PromptInstanceId { get; set; }

    public string OutputName { get; set; }

    public string ValidationRules { get; set; }

    public string ExampleOutput { get; set; }

    public virtual ICollection<OutputDetail> OutputDetails { get; set; } = new List<OutputDetail>();

    public virtual PromptInstance PromptInstance { get; set; }
}