// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Eduprompt.Domain.Entities;

public partial class Feedback
{
    public int FeedbackId { get; set; }

    public int PostId { get; set; }

    public int UserId { get; set; }

    public int? PackageId { get; set; }

    public int Rating { get; set; }

    public string Comment { get; set; }

    public DateTime CreatedDate { get; set; }

    public bool IsVerified { get; set; }

    public string Status { get; set; }

    public virtual Package Package { get; set; }

    public virtual Post Post { get; set; }

    public virtual User User { get; set; }
}