// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Eduprompt.Domain.Entities;

public partial class Message
{
    public int MessageId { get; set; }

    public int ConversationId { get; set; }

    public string SenderType { get; set; }

    public string Content { get; set; }

    public DateTime SentAt { get; set; }

    public bool IsRead { get; set; }

    public string Status { get; set; }

    public virtual Conversation Conversation { get; set; }
}