// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Eduprompt.Domain.Entities;

public partial class Order
{
    public int OrderId { get; set; }

    public int UserId { get; set; }

    public string OrderNumber { get; set; }

    public decimal TotalAmount { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime OrderDate { get; set; }

    public string Status { get; set; }

    // public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>(); // Removed - OrderDetail entity deleted

    // public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>(); // Removed - Payment entity deleted

    public virtual User User { get; set; }
}