// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Eduprompt.Domain.Entities;

public partial class OutputDetail
{
    public int DetailId { get; set; }

    public int OutputId { get; set; }

    public string DetailKey { get; set; }

    public string DetailValue { get; set; }

    public string DetailType { get; set; }

    public virtual ExpectedOutput Output { get; set; }
}