// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Eduprompt.Domain.Entities;

public partial class PackageDetail
{
    public int DetailId { get; set; }

    public int PackageId { get; set; }

    public string FeatureName { get; set; }

    public string FeatureValue { get; set; }

    public string FeatureType { get; set; }

    public virtual Package Package { get; set; }
}