// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Eduprompt.Domain.Entities;

public partial class Package
{
    public int PackageId { get; set; }

    public int? CategoryId { get; set; }

    public string PackageName { get; set; }

    public string Description { get; set; }

    public decimal Price { get; set; }

    public int? DurationDays { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual ICollection<Apikey> Apikeys { get; set; } = new List<Apikey>();

    public virtual ICollection<CartDetail> CartDetails { get; set; } = new List<CartDetail>();

    public virtual PackageCategory Category { get; set; }

    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<PackageDetail> PackageDetails { get; set; } = new List<PackageDetail>();

    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();

    public virtual ICollection<PromptInstance> PromptInstances { get; set; } = new List<PromptInstance>();

    public virtual ICollection<StorageTemplate> StorageTemplates { get; set; } = new List<StorageTemplate>();

    public virtual ICollection<Wishlist> Wishlists { get; set; } = new List<Wishlist>();
}