// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Eduprompt.Domain.Entities;

public partial class PaymentMethod
{
    public int PaymentMethodId { get; set; }

    public string MethodName { get; set; }

    public string Provider { get; set; }

    public bool IsActive { get; set; }

    public decimal? ProcessingFee { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}