// <auto-generated> New entity for payments </auto-generated>
#nullable disable
using System;

namespace Eduprompt.Domain.Entities;

public partial class Payment
{
    public int PaymentId { get; set; }
    public int? OrderId { get; set; }
    public int? UserId { get; set; }
    public decimal Amount { get; set; }
    public string PaymentMethod { get; set; }
    public string Provider { get; set; }
    public string Status { get; set; }
    public DateTime CreatedAt { get; set; }
    public DateTime? UpdatedAt { get; set; }

    // Provider-specific fields (VNPay)
    public string TransactionNo { get; set; }
    public string ResponseCode { get; set; }
    public string BankCode { get; set; }
    public string PayDate { get; set; }
    public string TxnRef { get; set; }

    public virtual Order Order { get; set; }
    public virtual User User { get; set; }
}


