// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Eduprompt.Domain.Entities;

public partial class Post
{
    public int PostId { get; set; }

    public int UserId { get; set; }

    public int? PackageId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public int ViewCount { get; set; }

    public DateTime PublishedAt { get; set; }

    public string Status { get; set; }

    public string PostType { get; set; }

    public string Tags { get; set; }

    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    public virtual Package Package { get; set; }

    public virtual User User { get; set; }
}