// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Eduprompt.Domain.Entities;

public partial class PromptInstanceDetail
{
    public int DetailId { get; set; }

    public int InstanceId { get; set; }

    public string ParameterName { get; set; }

    public string ParameterValue { get; set; }

    public string ParameterType { get; set; }

    public virtual PromptInstance Instance { get; set; }
}