// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Eduprompt.Domain.Entities;

public partial class PromptInstance
{
    public int InstanceId { get; set; }

    public int UserId { get; set; }

    public int PackageId { get; set; }

    public string PromptName { get; set; }

    public string InputJson { get; set; }

    public string OutputJson { get; set; }

    public DateTime ExecutedAt { get; set; }

    public int? ProcessingTimeMs { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Aihistory> Aihistories { get; set; } = new List<Aihistory>();

    public virtual ICollection<ExpectedOutput> ExpectedOutputs { get; set; } = new List<ExpectedOutput>();

    public virtual Package Package { get; set; }

    public virtual ICollection<PromptInstanceDetail> PromptInstanceDetails { get; set; } = new List<PromptInstanceDetail>();

    public virtual User User { get; set; }
}