// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Eduprompt.Domain.Entities;

public partial class StorageTemplate
{
    public int StorageId { get; set; }

    public int UserId { get; set; }

    public int TemplateId { get; set; }

    public DateTime? UploadDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string Status { get; set; }

    // public virtual PromptTemplate Template { get; set; } // Removed - PromptTemplate entity deleted

    public virtual User User { get; set; }
}