// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Eduprompt.Domain.Entities;

public partial class StorageTemplate
{
    public int StorageId { get; set; }

    public int UserId { get; set; }

    public int PackageId { get; set; }

    public string TemplateName { get; set; }

    public bool IsFavorite { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Package Package { get; set; }

    public virtual ICollection<TemplateArchitecture> TemplateArchitectures { get; set; } = new List<TemplateArchitecture>();

    public virtual User User { get; set; }
}