// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Eduprompt.Domain.Entities;

public partial class TemplateArchitecture
{
    public int ArchitectureId { get; set; }

    public int StorageId { get; set; }

    public string ArchitectureName { get; set; }

    public string ArchitectureType { get; set; }

    public string ConfigurationJson { get; set; }

    public virtual StorageTemplate Storage { get; set; }
}