// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Eduprompt.Domain.Entities;

public partial class Transaction
{
    public int TransactionId { get; set; }

    public int PaymentMethodId { get; set; }

    public int WalletId { get; set; }

    public int? OrderId { get; set; }

    public decimal Amount { get; set; }

    public string TransactionType { get; set; }

    public DateTime TransactionDate { get; set; }

    public string Status { get; set; }

    public string TransactionReference { get; set; }

    public virtual Order Order { get; set; }

    public virtual PaymentMethod PaymentMethod { get; set; }

    public virtual Wallet Wallet { get; set; }
}