// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Eduprompt.Domain.Entities;

public partial class User
{
    public int UserId { get; set; }

    public int? RoleId { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string ProfileUrl { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string Status { get; set; }

    public string Password { get; set; }

    public string GoogleId { get; set; }

    public string RefreshToken { get; set; }

    public DateTime? RefreshTokenExpiryTime { get; set; }

    public virtual Cart Cart { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    // public virtual ICollection<PromptTemplate> PromptTemplates { get; set; } = new List<PromptTemplate>(); // Removed - PromptTemplate entity deleted

    // public virtual ICollection<Review> Reviews { get; set; } = new List<Review>(); // Removed - Review entity deleted

    public virtual Role Role { get; set; }

    public virtual ICollection<StorageTemplate> StorageTemplates { get; set; } = new List<StorageTemplate>();

    public virtual ICollection<Wishlist> Wishlists { get; set; } = new List<Wishlist>();

    // New navigation properties
    public virtual Wallet Wallet { get; set; }
    public virtual ICollection<PaymentMethod> PaymentMethods { get; set; } = new List<PaymentMethod>();
    public virtual ICollection<Conversation> Conversations { get; set; } = new List<Conversation>();
    public virtual ICollection<AIHistory> AIHistories { get; set; } = new List<AIHistory>();
    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();
    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();
    public virtual ICollection<PromptInstance> PromptInstances { get; set; } = new List<PromptInstance>();
}