// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Eduprompt.Domain.Entities;

public partial class Wishlist
{
    public int WishlistId { get; set; }

    public int UserId { get; set; }

    public int PackageId { get; set; }

    public DateTime AddedAt { get; set; }

    public string Notes { get; set; }

    public virtual Package Package { get; set; }

    public virtual User User { get; set; }
}