// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Eduprompt.Domain.Entities;

public partial class Wishlist
{
    public int WishlistId { get; set; }

    public int UserId { get; set; }

    public int TemplateId { get; set; }

    public string WishlistName { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string Status { get; set; }

    public virtual StorageTemplate Template { get; set; }

    public virtual User User { get; set; }
}