// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Eduprompt.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;

namespace Eduprompt.DAL.DbContexts;

public partial class EdupromptV2Context : DbContext
{
    public EdupromptV2Context()
    {
    }

    public EdupromptV2Context(DbContextOptions<EdupromptV2Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Aihistory> Aihistories { get; set; }

    public virtual DbSet<Apikey> Apikeys { get; set; }

    public virtual DbSet<Cart> Carts { get; set; }

    public virtual DbSet<CartDetail> CartDetails { get; set; }

    public virtual DbSet<Conversation> Conversations { get; set; }

    public virtual DbSet<ExpectedOutput> ExpectedOutputs { get; set; }

    public virtual DbSet<Feedback> Feedbacks { get; set; }

    public virtual DbSet<Message> Messages { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OutputDetail> OutputDetails { get; set; }

    public virtual DbSet<Package> Packages { get; set; }

    public virtual DbSet<PackageCategory> PackageCategories { get; set; }

    public virtual DbSet<PackageDetail> PackageDetails { get; set; }

    public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }

    public virtual DbSet<Post> Posts { get; set; }

    public virtual DbSet<PromptInstance> PromptInstances { get; set; }

    public virtual DbSet<PromptInstanceDetail> PromptInstanceDetails { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<StorageTemplate> StorageTemplates { get; set; }

    public virtual DbSet<TemplateArchitecture> TemplateArchitectures { get; set; }

    public virtual DbSet<Transaction> Transactions { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<Wallet> Wallets { get; set; }

    public virtual DbSet<Wishlist> Wishlists { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Aihistory>(entity =>
        {
            entity.HasKey(e => e.AihistoryId).HasName("PK__AIHistor__F21B5160D1C55963");

            entity.ToTable("AIHistories");

            entity.HasIndex(e => e.ConversationId, "IX_AIHistories_ConversationID");

            entity.HasIndex(e => e.PromptInstanceId, "IX_AIHistories_PromptInstanceID");

            entity.HasIndex(e => e.UserId, "IX_AIHistories_UserID");

            entity.Property(e => e.AihistoryId).HasColumnName("AIHistoryID");
            entity.Property(e => e.Airesponse).HasColumnName("AIResponse");
            entity.Property(e => e.ConversationId).HasColumnName("ConversationID");
            entity.Property(e => e.ExecutedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.PromptInstanceId).HasColumnName("PromptInstanceID");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValue("Completed");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Conversation).WithMany(p => p.Aihistories)
                .HasForeignKey(d => d.ConversationId)
                .HasConstraintName("FK_AIHistories_Conversations");

            entity.HasOne(d => d.PromptInstance).WithMany(p => p.Aihistories)
                .HasForeignKey(d => d.PromptInstanceId)
                .HasConstraintName("FK_AIHistories_PromptInstances");

            entity.HasOne(d => d.User).WithMany(p => p.Aihistories)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AIHistories_Users");
        });

        modelBuilder.Entity<Apikey>(entity =>
        {
            entity.HasKey(e => e.ApikeyId).HasName("PK__APIKeys__C5971C76D87197CE");

            entity.ToTable("APIKeys");

            entity.HasIndex(e => e.PackageId, "IX_APIKeys_PackageID");

            entity.Property(e => e.ApikeyId).HasColumnName("APIKeyID");
            entity.Property(e => e.Apiprovider)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("APIProvider");
            entity.Property(e => e.KeyHash)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.PackageId).HasColumnName("PackageID");

            entity.HasOne(d => d.Package).WithMany(p => p.Apikeys)
                .HasForeignKey(d => d.PackageId)
                .HasConstraintName("FK_APIKeys_Packages");
        });

        modelBuilder.Entity<Cart>(entity =>
        {
            entity.HasKey(e => e.CartId).HasName("PK__Carts__51BCD7B72367E696");

            entity.HasIndex(e => e.UserId, "IX_Carts_UserId");

            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValue("Active");
            entity.Property(e => e.TotalItem).HasDefaultValue(0);

            entity.HasOne(d => d.User).WithMany(p => p.Carts)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_Carts_Users");
        });

        modelBuilder.Entity<CartDetail>(entity =>
        {
            entity.HasKey(e => e.CartDetailId).HasName("PK__CartDeta__01B6A6B4A158BB23");

            entity.HasIndex(e => e.CartId, "IX_CartDetails_CartId");

            entity.HasIndex(e => e.PackageId, "IX_CartDetails_PackageID");

            entity.Property(e => e.AddedDate).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.PackageId).HasColumnName("PackageID");
            entity.Property(e => e.Quantity).HasDefaultValue(1);
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Cart).WithMany(p => p.CartDetails)
                .HasForeignKey(d => d.CartId)
                .HasConstraintName("FK_CartDetails_Carts");

            entity.HasOne(d => d.Package).WithMany(p => p.CartDetails)
                .HasForeignKey(d => d.PackageId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CartDetails_Packages");
        });

        modelBuilder.Entity<Conversation>(entity =>
        {
            entity.HasKey(e => e.ConversationId).HasName("PK__Conversa__C050D897C34E1406");

            entity.HasIndex(e => e.UserId, "IX_Conversations_UserID");

            entity.Property(e => e.ConversationId).HasColumnName("ConversationID");
            entity.Property(e => e.StartedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValue("Active");
            entity.Property(e => e.Title).HasMaxLength(200);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.User).WithMany(p => p.Conversations)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_Conversations_Users");
        });

        modelBuilder.Entity<ExpectedOutput>(entity =>
        {
            entity.HasKey(e => e.OutputId).HasName("PK__Expected__CE760946F2288C89");

            entity.HasIndex(e => e.PromptInstanceId, "IX_ExpectedOutputs_PromptInstanceID");

            entity.Property(e => e.OutputId).HasColumnName("OutputID");
            entity.Property(e => e.OutputName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PromptInstanceId).HasColumnName("PromptInstanceID");

            entity.HasOne(d => d.PromptInstance).WithMany(p => p.ExpectedOutputs)
                .HasForeignKey(d => d.PromptInstanceId)
                .HasConstraintName("FK_ExpectedOutputs_PromptInstances");
        });

        modelBuilder.Entity<Feedback>(entity =>
        {
            entity.HasKey(e => e.FeedbackId).HasName("PK__Feedback__6A4BEDF6593A3347");

            entity.HasIndex(e => e.PackageId, "IX_Feedbacks_PackageID");

            entity.HasIndex(e => e.PostId, "IX_Feedbacks_PostID");

            entity.HasIndex(e => e.UserId, "IX_Feedbacks_UserID");

            entity.Property(e => e.FeedbackId).HasColumnName("FeedbackID");
            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.PackageId).HasColumnName("PackageID");
            entity.Property(e => e.PostId).HasColumnName("PostID");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValue("Active");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Package).WithMany(p => p.Feedbacks)
                .HasForeignKey(d => d.PackageId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Feedbacks_Packages");

            entity.HasOne(d => d.Post).WithMany(p => p.Feedbacks)
                .HasForeignKey(d => d.PostId)
                .HasConstraintName("FK_Feedbacks_Posts");

            entity.HasOne(d => d.User).WithMany(p => p.Feedbacks)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Feedbacks_Users");
        });

        modelBuilder.Entity<Message>(entity =>
        {
            entity.HasKey(e => e.MessageId).HasName("PK__Messages__C87C037CFD0C9767");

            entity.HasIndex(e => e.ConversationId, "IX_Messages_ConversationID");

            entity.Property(e => e.MessageId).HasColumnName("MessageID");
            entity.Property(e => e.Content).IsRequired();
            entity.Property(e => e.ConversationId).HasColumnName("ConversationID");
            entity.Property(e => e.SenderType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.SentAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValue("Sent");

            entity.HasOne(d => d.Conversation).WithMany(p => p.Messages)
                .HasForeignKey(d => d.ConversationId)
                .HasConstraintName("FK_Messages_Conversations");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.OrderId).HasName("PK__Orders__C3905BCF8F45086D");

            entity.HasIndex(e => e.PackageId, "IX_Orders_PackageID");

            entity.HasIndex(e => e.Status, "IX_Orders_Status");

            entity.HasIndex(e => e.UserId, "IX_Orders_UserId");

            entity.Property(e => e.OrderDate).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.PackageId).HasColumnName("PackageID");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValue("Pending");
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Package).WithMany(p => p.Orders)
                .HasForeignKey(d => d.PackageId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Orders_Packages");

            entity.HasOne(d => d.User).WithMany(p => p.Orders)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_Orders_Users");
        });

        modelBuilder.Entity<OutputDetail>(entity =>
        {
            entity.HasKey(e => e.DetailId).HasName("PK__OutputDe__135C314D37A22402");

            entity.HasIndex(e => e.OutputId, "IX_OutputDetails_OutputID");

            entity.Property(e => e.DetailId).HasColumnName("DetailID");
            entity.Property(e => e.DetailKey)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.DetailType)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("Text");
            entity.Property(e => e.DetailValue).IsRequired();
            entity.Property(e => e.OutputId).HasColumnName("OutputID");

            entity.HasOne(d => d.Output).WithMany(p => p.OutputDetails)
                .HasForeignKey(d => d.OutputId)
                .HasConstraintName("FK_OutputDetails_ExpectedOutputs");
        });

        modelBuilder.Entity<Package>(entity =>
        {
            entity.HasKey(e => e.PackageId).HasName("PK__Packages__322035ECCBC95752");

            entity.HasIndex(e => e.CategoryId, "IX_Packages_CategoryID");

            entity.HasIndex(e => e.IsActive, "IX_Packages_IsActive");

            entity.Property(e => e.PackageId).HasColumnName("PackageID");
            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.PackageName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Category).WithMany(p => p.Packages)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Packages_Categories");
        });

        modelBuilder.Entity<PackageCategory>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("PK__PackageC__19093A2B86DCCBC2");

            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<PackageDetail>(entity =>
        {
            entity.HasKey(e => e.DetailId).HasName("PK__PackageD__135C314D5583EF6A");

            entity.HasIndex(e => e.PackageId, "IX_PackageDetails_PackageID");

            entity.Property(e => e.DetailId).HasColumnName("DetailID");
            entity.Property(e => e.FeatureName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.FeatureType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.FeatureValue)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.PackageId).HasColumnName("PackageID");

            entity.HasOne(d => d.Package).WithMany(p => p.PackageDetails)
                .HasForeignKey(d => d.PackageId)
                .HasConstraintName("FK_PackageDetails_Packages");
        });

        modelBuilder.Entity<PaymentMethod>(entity =>
        {
            entity.HasKey(e => e.PaymentMethodId).HasName("PK__PaymentM__DC31C1F363C9C53F");

            entity.Property(e => e.PaymentMethodId).HasColumnName("PaymentMethodID");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.MethodName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ProcessingFee)
                .HasDefaultValue(0.00m)
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Provider)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Post>(entity =>
        {
            entity.HasKey(e => e.PostId).HasName("PK__Posts__AA126038DA453842");

            entity.HasIndex(e => e.PackageId, "IX_Posts_PackageID");

            entity.HasIndex(e => e.Status, "IX_Posts_Status");

            entity.HasIndex(e => e.UserId, "IX_Posts_UserID");

            entity.Property(e => e.PostId).HasColumnName("PostID");
            entity.Property(e => e.Content).IsRequired();
            entity.Property(e => e.PackageId).HasColumnName("PackageID");
            entity.Property(e => e.PostType)
                .HasMaxLength(50)
                .HasDefaultValue("General");
            entity.Property(e => e.PublishedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValue("Published");
            entity.Property(e => e.Tags).HasMaxLength(500);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Package).WithMany(p => p.Posts)
                .HasForeignKey(d => d.PackageId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Posts_Packages");

            entity.HasOne(d => d.User).WithMany(p => p.Posts)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_Posts_Users");
        });

        modelBuilder.Entity<PromptInstance>(entity =>
        {
            entity.HasKey(e => e.InstanceId).HasName("PK__PromptIn__5C51996FB4F8AA30");

            entity.HasIndex(e => e.PackageId, "IX_PromptInstances_PackageID");

            entity.HasIndex(e => e.UserId, "IX_PromptInstances_UserID");

            entity.Property(e => e.InstanceId).HasColumnName("InstanceID");
            entity.Property(e => e.ExecutedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.PackageId).HasColumnName("PackageID");
            entity.Property(e => e.PromptName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValue("Completed");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Package).WithMany(p => p.PromptInstances)
                .HasForeignKey(d => d.PackageId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PromptInstances_Packages");

            entity.HasOne(d => d.User).WithMany(p => p.PromptInstances)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_PromptInstances_Users");
        });

        modelBuilder.Entity<PromptInstanceDetail>(entity =>
        {
            entity.HasKey(e => e.DetailId).HasName("PK__PromptIn__135C314DEB2B3C05");

            entity.HasIndex(e => e.InstanceId, "IX_PromptInstanceDetails_InstanceID");

            entity.Property(e => e.DetailId).HasColumnName("DetailID");
            entity.Property(e => e.InstanceId).HasColumnName("InstanceID");
            entity.Property(e => e.ParameterName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ParameterType)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("Text");
            entity.Property(e => e.ParameterValue).IsRequired();

            entity.HasOne(d => d.Instance).WithMany(p => p.PromptInstanceDetails)
                .HasForeignKey(d => d.InstanceId)
                .HasConstraintName("FK_PromptInstanceDetails_PromptInstances");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Roles__8AFACE1AFCD0E6DA");

            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Status).HasMaxLength(50);
        });

        modelBuilder.Entity<StorageTemplate>(entity =>
        {
            entity.HasKey(e => e.StorageId).HasName("PK__StorageT__8A247E37F10CB4C4");

            entity.HasIndex(e => e.PackageId, "IX_StorageTemplates_PackageID");

            entity.HasIndex(e => e.UserId, "IX_StorageTemplates_UserID");

            entity.Property(e => e.StorageId).HasColumnName("StorageID");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.PackageId).HasColumnName("PackageID");
            entity.Property(e => e.TemplateName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.TemplateContent);
            entity.Property(e => e.Grade).HasMaxLength(10);
            entity.Property(e => e.Subject).HasMaxLength(50);
            entity.Property(e => e.Chapter).HasMaxLength(100);
            entity.Property(e => e.IsPublic).HasDefaultValue(false);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Package).WithMany(p => p.StorageTemplates)
                .HasForeignKey(d => d.PackageId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StorageTemplates_Packages");

            entity.HasOne(d => d.User).WithMany(p => p.StorageTemplates)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_StorageTemplates_Users");
        });

        modelBuilder.Entity<TemplateArchitecture>(entity =>
        {
            entity.HasKey(e => e.ArchitectureId).HasName("PK__Template__1507D9AAECAE3488");

            entity.HasIndex(e => e.StorageId, "IX_TemplateArchitectures_StorageID");

            entity.Property(e => e.ArchitectureId).HasColumnName("ArchitectureID");
            entity.Property(e => e.ArchitectureName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ArchitectureType)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("Sequential");
            entity.Property(e => e.StorageId).HasColumnName("StorageID");

            entity.HasOne(d => d.Storage).WithMany(p => p.TemplateArchitectures)
                .HasForeignKey(d => d.StorageId)
                .HasConstraintName("FK_TemplateArchitectures_StorageTemplates");
        });

        modelBuilder.Entity<Transaction>(entity =>
        {
            entity.HasKey(e => e.TransactionId).HasName("PK__Transact__55433A4BC116F561");

            entity.HasIndex(e => e.OrderId, "IX_Transactions_OrderID");

            entity.HasIndex(e => e.Status, "IX_Transactions_Status");

            entity.HasIndex(e => e.WalletId, "IX_Transactions_WalletID");

            entity.Property(e => e.TransactionId).HasColumnName("TransactionID");
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.OrderId).HasColumnName("OrderID");
            entity.Property(e => e.PaymentMethodId).HasColumnName("PaymentMethodID");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValue("Pending");
            entity.Property(e => e.TransactionDate).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.TransactionReference).HasMaxLength(100);
            entity.Property(e => e.TransactionType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.WalletId).HasColumnName("WalletID");

            entity.HasOne(d => d.Order).WithMany(p => p.Transactions)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK_Transactions_Orders");

            entity.HasOne(d => d.PaymentMethod).WithMany(p => p.Transactions)
                .HasForeignKey(d => d.PaymentMethodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Transactions_PaymentMethods");

            entity.HasOne(d => d.Wallet).WithMany(p => p.Transactions)
                .HasForeignKey(d => d.WalletId)
                .HasConstraintName("FK_Transactions_Wallets");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CC4C4292200F");

            entity.HasIndex(e => e.Email, "IX_Users_Email");

            entity.HasIndex(e => e.RoleId, "IX_Users_RoleId");

            entity.HasIndex(e => e.Email, "UQ__Users__A9D10534DE632851").IsUnique();

            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.GoogleId).HasMaxLength(100);
            entity.Property(e => e.Password).HasMaxLength(500);
            entity.Property(e => e.Phone).HasMaxLength(20);
            entity.Property(e => e.ProfileUrl).HasMaxLength(500);
            entity.Property(e => e.RefreshToken).HasMaxLength(500);
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValue("Active");

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Users_Roles");
        });

        modelBuilder.Entity<Wallet>(entity =>
        {
            entity.HasKey(e => e.WalletId).HasName("PK__Wallets__84D4F92E4DDF0EC5");

            entity.HasIndex(e => e.UserId, "IX_Wallets_UserId");

            entity.Property(e => e.WalletId).HasColumnName("WalletID");
            entity.Property(e => e.Balance).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Currency)
                .IsRequired()
                .HasMaxLength(10)
                .HasDefaultValue("VND");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValue("Active");

            entity.HasOne(d => d.User).WithMany(p => p.Wallets)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_Wallets_Users");
        });

        modelBuilder.Entity<Wishlist>(entity =>
        {
            entity.HasKey(e => e.WishlistId).HasName("PK__Wishlist__233189EBA75C6810");

            entity.HasIndex(e => e.PackageId, "IX_Wishlists_PackageID");

            entity.HasIndex(e => e.UserId, "IX_Wishlists_UserId");

            entity.Property(e => e.AddedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.PackageId).HasColumnName("PackageID");

            entity.HasOne(d => d.Package).WithMany(p => p.Wishlists)
                .HasForeignKey(d => d.PackageId)
                .HasConstraintName("FK_Wishlists_Packages");

            entity.HasOne(d => d.User).WithMany(p => p.Wishlists)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_Wishlists_Users");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}