// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Eduprompt.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

public partial class EdupromptContext : DbContext
{
    public EdupromptContext()
    {
    }

    public EdupromptContext(DbContextOptions<EdupromptContext> options)
        : base(options)
    {
    }

    // Core entities
    public virtual DbSet<User> Users { get; set; }
    public virtual DbSet<Role> Roles { get; set; }
    
    // E-commerce entities
    public virtual DbSet<Cart> Carts { get; set; }
    public virtual DbSet<CartDetail> CartDetails { get; set; }
    public virtual DbSet<Order> Orders { get; set; }
    public virtual DbSet<Wishlist> Wishlists { get; set; }
    
    // Payment entities
    public virtual DbSet<Wallet> Wallets { get; set; }
    // public virtual DbSet<PaymentMethod> PaymentMethods { get; set; } // Temporarily disabled due to UserId column issue
    public virtual DbSet<Transaction> Transactions { get; set; }
    
    // AI/Prompt entities
    public virtual DbSet<StorageTemplate> StorageTemplates { get; set; }
    public virtual DbSet<PromptInstance> PromptInstances { get; set; }
    public virtual DbSet<PromptInstanceDetail> PromptInstanceDetails { get; set; }
    public virtual DbSet<TemplateArchitecture> TemplateArchitectures { get; set; }
    public virtual DbSet<AIHistory> AIHistories { get; set; }
    public virtual DbSet<ExpectedOutput> ExpectedOutputs { get; set; }
    public virtual DbSet<OutputDetail> OutputDetails { get; set; }
    
    // Package entities
    public virtual DbSet<Package> Packages { get; set; }
    public virtual DbSet<PackageCategory> PackageCategories { get; set; }
    public virtual DbSet<PackageDetail> PackageDetails { get; set; }
    public virtual DbSet<APIKey> APIKeys { get; set; }
    
    // Communication entities
    public virtual DbSet<Conversation> Conversations { get; set; }
    public virtual DbSet<Message> Messages { get; set; }
    
    // Content entities
    public virtual DbSet<Post> Posts { get; set; }
    public virtual DbSet<Feedback> Feedbacks { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            // This will be configured in Program.cs
        }
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // Basic configurations - let EF Core handle most relationships automatically
        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId);
            entity.Property(e => e.Email).IsRequired().HasMaxLength(255);
            entity.Property(e => e.FullName).IsRequired().HasMaxLength(255);
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId);
            entity.Property(e => e.RoleName).IsRequired().HasMaxLength(50);
        });

        // PaymentMethod configuration
        modelBuilder.Entity<PaymentMethod>(entity =>
        {
            entity.HasKey(e => e.PaymentMethodID);
            entity.Property(e => e.MethodName).IsRequired().HasMaxLength(100);
            entity.Property(e => e.Provider).IsRequired().HasMaxLength(50);
            entity.Property(e => e.ProcessingFee).HasColumnType("decimal(18,2)");
            
            // Explicitly ignore any shadow properties that EF might try to create
            entity.Ignore("UserId");
        });

        // Transaction configuration
        modelBuilder.Entity<Transaction>(entity =>
        {
            entity.HasKey(e => e.TransactionID);
            entity.Property(e => e.Amount).HasColumnType("decimal(18,2)");
            entity.Property(e => e.TransactionType).IsRequired().HasMaxLength(50);
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.TransactionReference).HasMaxLength(100);
        });

        // Add other basic configurations as needed
        base.OnModelCreating(modelBuilder);
    }
}